-- my_wb_slave.vhd — a HAND-WRITTEN Wishbone B4 classic slave.
--
-- This file is NOT generated by ISACLE.  It is authored independently and dropped
-- into the SoC via 'externEntity' + 'attachSlave' — the whole point of the
-- exercise: a block written to the Wishbone signalling contract instantiates
-- pin-for-pin.  Port names match the WbSlaveIn/WbSlaveOut bundles (plus the
-- domain's clk/reset, dom10mhz/rst).
--
-- Behaviour: on a strobed cycle it inserts 4 wait states, then asserts ack for
-- the transfer and presents 0x3B (=59) on the read data bus.  Before ack the read
-- data reads 0x00 — so a master that failed to wait for ack would sample 0, and
-- reading 59 proves the CPU honoured the classic ACK handshake.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity my_wb_slave is
    port (
        wb_clk_i : in  std_logic;
        wb_rst_i : in  std_logic;
        wb_cyc_i : in  std_logic;
        wb_stb_i : in  std_logic;
        wb_we_i  : in  std_logic;
        wb_adr_i : in  unsigned(31 downto 0);
        wb_dat_i : in  unsigned(7 downto 0);
        wb_dat_o : out unsigned(7 downto 0);
        wb_ack_o : out std_logic
    );
end entity my_wb_slave;

architecture rtl of my_wb_slave is
    constant WAITS   : unsigned(3 downto 0) := to_unsigned(4, 4);
    signal   cnt     : unsigned(3 downto 0) := (others => '0');
    signal   active  : std_logic;
    signal   done    : std_logic;
begin
    active <= wb_cyc_i and wb_stb_i;                 -- this slave is being accessed
    done   <= '1' when cnt >= WAITS else '0';        -- wait states elapsed

    process (wb_clk_i)
    begin
        if rising_edge(wb_clk_i) then
            if wb_rst_i = '1' then
                cnt <= (others => '0');
            elsif active = '1' then
                if done = '0' then
                    cnt <= cnt + 1;                  -- count out the wait states
                end if;
            else
                cnt <= (others => '0');              -- idle: rearm for next access
            end if;
        end if;
    end process;

    wb_ack_o <= active and done;                     -- terminate the transfer
    wb_dat_o <= to_unsigned(59, 8) when (active = '1' and done = '1')
                else to_unsigned(0, 8);              -- data valid only with ack
end architecture rtl;
